// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.wudi.spring.springbootstart.shengsiyuan.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wudi.spring.springbootstart.shengsiyuan.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  String getRealname();
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
