// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.wudi.spring.springbootstart.shengsiyuan.grpc;

public final class PersonProtoA {
  private PersonProtoA() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Person.proto\022+com.wudi.spring.factories.springbo" +
      "otstart.shengsiyuan\"\035\n\tMyRequest\022\020\n\010user" +
      "name\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010realname\030\002 \001" +
      "(\t2\235\001\n\016StudentService\022\212\001\n\025GetRealNameByU" +
      "sername\0226.com.wudi.spring.factories.springbootstar" +
      "t.shengsiyuan.MyRequest\0327.com.wudi.sprin" +
      "g.springbootstart.shengsiyuan.MyResponse" +
      "\"\000BB\n0com.wudi.spring.factories.springbootstart.sh" +
      "engsiyuan.grpcB\014PersonProtoAP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wudi_spring_springbootstart_shengsiyuan_MyResponse_descriptor,
        new String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
